### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [dbjranger/splurty#1]
@dbjranger 

On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by dbjranger** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1">  added to application.html.erb
Looks awesome on mobile!

**Comment by dbjranger** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by dbjranger** [comment]
"<meta name="viewport" content="width=device-width, initial-scale=1">" was added to the head of the application.html.erb file

**Comment by dbjranger** [comment]
I added the following to the head of the application.html.erb file 

meta name="viewport" content="width=device-width, initial-scale=1"

**Comment by dbjranger** [comment]
Looks awesome on mobile!
